
- name: play level variables
  hosts: local
  connection: local # Ansible is connecting to localhost
  vars:
    COURSE: Ansible
    DURATION: 10HRS
    Trainer: pranathi
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Course Name is: {{ COURSE }}, Duratioin: {{ DURATION }}, Trainer: {{ Trainer }}"


